app4/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'message'
#url for app, add your URL Configuration

urlpatterns = [
    path('', views.message, name='index'),
    path('message_all_data/', views.message_all_data, name='message-all-data'),
    path('message_create/', views.message_create_data, name='message-create-data'),
    path('confirmation/', views.confirmation, name='confirmation'),
    path('prevention/', views.prevention, name='prevention'),
]

fact_checker/urls.py
from django.urls import path
from .views import info_all, info_detail, info_create, info_all_data,info_detail_data,info_create_data
#url for app
app_name = 'fact_checker'

urlpatterns = [
    path('', info_all, name='info-all'),
    path('info_all_data/',info_all_data, name='info-all-data'),
    path('detail/<int:id>/', info_detail, name='info-detail'),
    path('detail/<int:id>/data/', info_detail_data, name='info-detail-data'),
    path('create/', info_create, name='info-create'),
    path('create_post/',info_create_data, name='info-create-post' )
]

feedback/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path
from . import views
app_name = 'feedback'

urlpatterns = [
    path('', views.feedback, name='feedback'),
    path('all_feedback/', views.feedback_list, name='all_feedback'),
    path('create/', views.create, name='create'),
    path('landing/', views.landing, name='landing'),
]

relawan/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path
from . import views

app_name = 'relawan'

urlpatterns = [
    path('', views.info, name='relawan'),
    path('all_volunteer/', views.volunteer_list, name='all_volunteer'),
    path('buat/', views.buat, name='buat'),
    path('bisa/', views.bisa, name='bisa'),
    path('about/', views.about, name='About'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from covid_statistic.views import statistic_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', statistic_views, name='Statistic_Views'),
    path('', include('user.urls')),
    path('Fact-Checker/', include('fact_checker.urls')),
    path('statistic/', include('covid_statistic.urls')),
    path('message/', include('app4.urls')),
    path('feedback/', include('feedback.urls')),
    path('relawan/', include('relawan.urls')),
]

user/urls.py
from django.contrib import auth
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import register_view

#url for app

app_name = 'user'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('register/', register_view, name='register')
]

feedback/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    feedback = models.TextField()

feedback/forms.py
from django import forms

#import model dari models.py
from .models import Feedback

class FormFeedback(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = [
            'feedback',
        ]

        labels = {
            'feedback' : 'Kritik/Saran',
        }

        widgets = {

            'feedback' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'id'    : 'feedback',
                }
            ),
        }

feedback/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import FormFeedback
from .models import Feedback
from django.http import Http404
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory, modelformset_factory
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.core.serializers import serialize 

# Create your views here.
def feedback(request):
    form = FormFeedback()
    context = {
        'form': form,
    }
    return render(request, 'feedback.html', context)

def create(request):
    if request.method == 'POST':
        feedback = request.POST['feedback']
        # user_name = request.POST['user_name']
        response_data = dict()
        post = Feedback(user=request.user, feedback=feedback)
        post.save()
        return redirect('feedback:feedback')

def feedback_list(request):
    feedback= Feedback.objects.all()
    result = []
    for i in feedback:
        user = User.objects.get(id=i.user.id)
        temp = dict()
        temp['feedback'] = i.feedback
        temp['username'] = user.username
        result.append(temp)
    context = {
        'result': result,
    }
    return JsonResponse(context)

@login_required(login_url=('user:login'))
def landing(request):
    if request.method == "POST":
        form = FormFeedback(request.POST)
        context = {
            'form': form,
            'feedback': request.POST['feedback'],
            # 'user_name': request.POST['user_name'],
        }
        return render(request, 'landing.html', context)
    return redirect('feedback:feedback')

feedback/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}
    {% endblock title %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" 
  crossorigin="anonymous">
  {% block style %}
  {% endblock style %}

</head>

<style>
 .navbar-custom {
   background-color: #154360;
 }
 .navbar-custom .navbar-toggler-icon {
  background-image: url("https://files.catbox.moe/hpcipe.svg");
}

.copyright {
  font-size: 80%;
  color: rgb(229, 229, 229);

}
</style>

<body>
    <nav class="navbar navbar-custom navbar-expand-lg">
        <a style="color: white;" class="navbar-brand" href="{% url 'Statistic_Views' %}">COVINFO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a style="color: white;" class="nav-link" href="{% url 'Statistic_Views' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a style="color: white;" class="nav-link" href="{% url 'relawan:About' %}">About</a>
            </li>
            <li class="nav-item">
              <a style="color: white;" class="nav-link" href="{% url 'stats:stats_prov' %}">Cases</a>
            </li>
            <li class="nav-item">
              <a style="color: white;" class="nav-link" href="{% url 'message:prevention' %}">Prevention</a>
            </li>
            <li class="nav-item dropdown">
              <a style="color: white;" class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Other
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'fact_checker:info-all' %}">Fact Checker</a>
                <a class="dropdown-item" href="{% url 'relawan:relawan' %}">Volunteer</a>
                <a class="dropdown-item" href="{% url 'feedback:feedback' %}">Feedback</a>
                <a class="dropdown-item" href="{% url 'message:index' %}">Hopeful Message</a>
              </div>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                  <a style="color: white;" class="nav-link" href="#"> Hello, {{ user.username }} </a>
              </li>
              <li class="nav-item">
                  <a style="color: white;" class="nav-link"  href="{% url 'user:logout' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                  <a style="color: white;"  class="nav-link" href="{% url 'user:login' %}">Login</a>
              </li>
              <li class="nav-item">
                  <a style="color: white;" class="nav-link" href="{% url 'user:register' %}"> Register</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    <div class="container" >
        {% block content %}

        {% endblock content %}
      <br>
      <br>
      <p class="copyright">© Kelompok 14 PPW Kelas D 2020, Fakultas Ilmu Komputer, Universitas Indonesia</p>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 
integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" 
crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" 
integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" 
crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" 
integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" 
crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" 
integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" 
crossorigin="anonymous"></script>
  {% block extra_script %}
  {% endblock extra_script %}
</body>

</html>

feedback/templates/feedback.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    <title>Feedback</title>
{% endblock page_title %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'stylefb.css' %}">
{% endblock style %}

{% block content %}
    <h1>Feedback</h1>
    <br>
    <div class="container">
        <div class="row">
            <div id= "col1" class="col">
                <div class="column">
                    <div class="container-fluid">
                        <div id="scrollable">
                            <!-- Ajax Content -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="container-fluid">
                    <form action="{% url 'feedback:landing' %}" class="main-form" id="form" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <!-- <label for="name">Username</label>
                            <br>
                            {{ form.user_name }} -->
                            <label for="name">Kritik/Saran</label>
                            <br>
                            {{ form.feedback }}
                        </div>
                        <button id="addfeedback" type="submit" class="btn btn-dark mb-3 float-right">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'feedback.js' %}"></script>
    {% if not user.is_authenticated %}
        <script src="{% static 'hoverfeedback.js' %}"></script>
    {% endif %}
{% endblock extra_script %}

feedback/templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Confirmation</title>
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'stylefb.css' %}">
{% endblock style %}

{% block content %}
<div class="d-flex flex-column pt-5 align-items-center container wrapper">
    <div class="col-md-8">
        <form action=" {% url 'feedback:create' %}" class="main-form" method="POST">
            {% csrf_token %}
            <div class="d-none">
                {{ form }}
            </div>
            <div class="card text-center">
                <div class="card-header">
                    Confirmation
                </div>
                <div class="card-body">
                    <h5 class="card-title">Halo, {{ request.user.username }}</h5>
                    <p class="card-text">Tambahan feedback ini?</p>
                    <h4 class="text text-center" style="color: #FCA311;"><span>&#x201c</span>{{ feedback }}<span>&#x201d</span></h4>
                    <div class="d-flex justify-content-end">
                        <a id="cancelfeedback" href="{% url 'feedback:feedback' %}" class="btn btn-secondary mr-2">Cancel</a>
                        <button id="confirmfeedback" class="btn btn-dark mr-2" type="submit">Add</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock content %}