Volunteer/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path
from . import views

app_name = 'info'

urlpatterns = [
    path('', views.info, name='info'),
    path('all_volunteer/', views.volunteer_list, name='all_volunteer'),
    path('buat/', views.buat, name='buat'),
    path('bisa/', views.bisa, name='bisa'),
    path('about/', views.about, name='About'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from covid_statistic.views import statistic_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', statistic_views, name='Statistic_Views'),
    path('', include('user.urls')),
    path('Fact-Checker/', include('fact_checker.urls')),
    path('statistic/', include('covid_statistic.urls')),
    path('message/', include('app4.urls')),
    path('feedback/', include('feedback.urls')),
    path('relawan/', include('relawan.urls')),
]

Volunteer/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Volunteer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    volunteer = models.CharField(max_length=50)

Volunteer/forms.py
from django import forms

#import model dari models.py
from .models import Volunteer

class VolunteerForm(forms.ModelForm):
    class Meta:
        model = Volunteer
        fields = [
            'volunteer',
        ]

        labels = {
            'volunteer' : 'Tujuan/Kontak',
        }

        widgets = {

            'volunteer' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'id'    : 'volunteer',
                }
            ),
        }

Volunteer/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import inlineformset_factory, modelformset_factory
from django.http.response import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from .forms import VolunteerForm
from .models import Volunteer
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.core.serializers import serialize 

# Create your views here.
def about(request):
    return render(request, 'About.html')

def info(request):
    form = VolunteerForm()
    context = {
        'form': form,
    }
    return render(request, 'info.html', context)

def buat(request):
    if request.method == 'POST':
        volunteer = request.POST['volunteer']
        response_data = dict()
        post = Volunteer(user=request.user, volunteer=volunteer)
        post.save()
        return redirect('info:info')
    

def volunteer_list(request):
    volunteer = Volunteer.objects.all()
    result = []
    for i in volunteer:
        user = User.objects.get(id=i.user.id)
        temp = dict()
        temp['volunteer'] = i.volunteer
        temp['username'] = user.username
        result.append(temp)
    context = {
        'result': result,
    }
    return JsonResponse(context)

@login_required(login_url=('user:login'))
def bisa(request):
    if request.method == "POST":
        form = VolunteerForm(request.POST)
        context = {
            'form': form,
            'volunteer': request.POST['volunteer'],
        }
        return render(request, 'bisa.html', context)
    return redirect('info:info')

Volunteer/templates/About.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  <title>About</title>
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'about.css' %}">
{% endblock style %}

{% block content %}
<br>
<div class="row">
  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
    <img class="img-responsive" src="{% static 'covid.png' %}" >
  </div>
  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
      <h2 class="text">
        <b>Covinfo</b> akan memberikan informasi mengenai akumulasi 
        kasus covid-19 di setip provinsi di Indonesia. Covinfo dibuat oleh mahasiswa Fakultas Ilmu Komputer Universitas Indonesia untuk memenuhi tugas pada mata kuliah Program Perancangan Web semester 3. Melalu website ini diharapkan mampu memberi informasi kepada masyarakat Indonesia terkain kasus dan cara pencegahan penularan dari covid-19.
      </h2>
  </div>
</div>
{% endblock content %}

Volunteer/templates/bisa.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Konfirmasi</title>
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'lol.css' %}">
{% endblock style %}

{% block content %}
<div class="d-flex flex-column pt-5 align-items-center container wrapper">
    <div class="col-md-8">
        <form action=" {% url 'info:buat' %}" class="main-form" method="POST">
            {% csrf_token %}
            <div class="d-none">
                {{ form }}
            </div>
            <div class="card text-center">
                <div class="card-header">
                    Konfirmasi
                </div>
                <div class="card-body">
                    <h5 class="card-title">Halo, {{ request.user.username }}</h5>
                    <p class="card-text">Tambahkan Masukkan Volunteer?</p>
                    <h4 class="text text-center" style="color: #FCA311;"><span>&#x201c</span>{{ volunteer }}<span>&#x201d</span></h4>
                    <div class="d-flex justify-content-end">
                        <a id="cancelvolunteer" href="{% url 'info:info' %}" class="btn btn-secondary mr-2">Cancel</a>
                        <button id="confirmvolunteer" class="btn btn-dark mr-2" type="submit">Add</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock content %}

Volunteer/templates/info.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    <title>Volunteer</title>
{% endblock page_title %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'lol.css' %}">
{% endblock style %}

{% block content %}
    <h1 style="font-weight:bold;color: #154360;">Volunteer</h1>
    <div id="logon">
        <p class="d-flex justify-content-center mt-5" style="font-weight:bold;color: #154360;">Ingin Menjadi Volunteer atau Membutuhkan Volunteer? Mari isi Form!</p><a href ="#" id="ngerti" style="color:#154360;">Klik</a>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <div id= "col1" class="col">
                <div class="column">
                    <div class="container-fluid">
                        <h2 style="text-align: center;">Volunteer/Membutuhkan</h2>
                        <div id="scrollable">
                            <!-- Ajax Content -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="container-fluid">
                    <form action="{% url 'info:bisa' %}" class="main-form" id="form" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <br>
                            {{ form }}
                        </div>
                        <button id="volunteer" type="submit" class="btn btn-dark mb-3 float-right">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}


{% block extra_script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/Volunteer.js' %}"></script>
    {% if not user.is_authenticated %}
        <script src="{% static 'js/lol.js' %}"></script>
    {% endif %}
{% endblock extra_script %}