app4/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'message'
#url for app, add your URL Configuration

urlpatterns = [
    path('', views.message, name='index'),
    path('message_all_data/', views.message_all_data, name='message-all-data'),
    path('message_create/', views.message_create_data, name='message-create-data'),
    path('confirmation/', views.confirmation, name='confirmation'),
    path('prevention/', views.prevention, name='prevention'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from covid_statistic.views import statistic_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', statistic_views, name='Statistic_Views'),
    path('', include('user.urls')),
    path('Fact-Checker/', include('fact_checker.urls')),
    path('statistic/', include('covid_statistic.urls')),
    path('message/', include('app4.urls')),
    path('feedback/', include('feedback.urls')),
    path('relawan/', include('relawan.urls')),
]

app4/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class MessageAndExpectation(models.Model):
    
    #user and message
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    message = models.TextField()
    

app4/forms.py
from django import forms
from app4.models import MessageAndExpectation


class MessageAndExpectationForm(forms.ModelForm):
    class Meta:
        model = MessageAndExpectation
        fields = (
            'message',
        )

        widgets = {
            'message': forms.Textarea(attrs={'placeholder': 'Insert your message here..', 'id': 'message', 'class': 'form-control'}),
        }

app4/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import inlineformset_factory, modelformset_factory
from django.http.response import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from app4.forms import MessageAndExpectationForm
from app4.models import MessageAndExpectation
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.core.serializers import serialize 


# Create your views here.
def prevention(request):
    return render(request, 'prevention.html')

def message(request):
    form = MessageAndExpectationForm()
    context = {
        'form': form,
    }
    return render(request, 'message.html', context)

def message_all_data(request):
    message = MessageAndExpectation.objects.all()
    result = []
    for i in message:
        user = User.objects.get(id=i.user.id)
        temp = dict()
        temp['message'] = i.message
        temp['username'] = user.username
        result.append(temp)
    context = {
        'result': result,
    }
    return JsonResponse(context)

def message_create_data(request):
    if request.method == 'POST':
        message = request.POST.get('message')
        response_data = dict()
        post = MessageAndExpectation(user=request.user, message=message)
        post.save()
        return redirect('message:index')

@login_required(login_url=('user:login'))
def confirmation(request):
    if request.method == "POST":
        form = MessageAndExpectationForm(request.POST)
        context = {
            'form': form,
            'message': request.POST['message']
        }
        return render(request, 'confirmation.html', context)
    return redirect('message:index')

app4/templates/confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Confirmation</title>
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/message.css' %}">
{% endblock style %}

{% block content %}
<div class="d-flex flex-column pt-5 align-items-center container wrapper">
    <div class="col-md-8">
        <form action=" {% url 'message:message-create-data' %}" class="main-form" method="POST">
            {% csrf_token %}
            <div class="d-none">
                {{ form }}
            </div>
            <div class="card text-center">
                <div class="card-header">
                    Confirmation
                </div>
                <div class="card-body">
                    <h5 class="card-title">Halo, {{ request.user.username }}</h5>
                    <p class="card-text">Tambahkan pesan ini?</p>
                    <h4 class="text text-center" style="color: #FCA311;"><span>&#x201c</span>{{ message }}<span>&#x201d</span></h4>
                    <div class="d-flex justify-content-end">
                        <a id="cancelmessage" href="{% url 'message:index' %}" class="btn btn-secondary mr-2">Batal</a>
                        <button id="confirmmessage" class="btn btn-dark mr-2" type="submit">Tambah</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock content %}

app4/templates/message.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Message</title>
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/message.css' %}">
{% endblock style %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="column">
            <div class="container-fluid">
                <h2 class="text-center">Kolom Pesan</h2>
                <form action="{% url 'message:confirmation' %}" class="main-form" id="form" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Pesan</label>
                        <br>
                        {{ form.message }}
                    </div>
                    <button id="addmessage" type="submit" class="btn btn-dark mb-3 float-right">Tambah</button>
                </form>
            </div>
        </div>
        <div class="column">
            <div class="container-fluid">
                <h2 style="text-align: center;">Pesan dan Harapan</h2>
                <div id="scrollable">
                    <!-- Ajax Content -->
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block extra_script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/message.js' %}"></script>
    {% if not user.is_authenticated %}
        <script src="{% static 'js/hovermessage.js' %}"></script>
    {% endif %}
{% endblock extra_script %}

app4/templates/prevention.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Confirmation</title>
{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/prevention.css' %}">
{% endblock style %}

{% block content %}

<div class="container-fluid">
    <div class="d-flex justify-content-center">
        <div class="col-3 ml-2">
            <div class="container-fluid">
                <img src="{% static 'img/1_Xn_7ZpYbGAszWlotIOhLIQ.jpeg' %}" class="img-fluid" alt="Responsive image">
                <div class="block">
                    <p>Menggunakan Masker</p>
                </div>
            </div>
        </div>
        <div class="col-3 ml-2">
            <div class="container-fluid">
                <img src="{% static 'img/physical-distancing-4986940_1280.jpg' %}"  class="img-fluid" alt="Responsive image">
                <div class="block">
                    <p>Menjaga Jarak</p>
                </div>
            </div>
        </div>
        <div class="col-3 ml-2">
            <div class="container-fluid">
                <img src="{% static 'img/Eck83SEXoAATDcE.jpg' %}"  class="img-fluid" alt="Responsive image">
                <div class="block">
                    <p>Mencuci Tangan</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}